#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with a sleep 2 in btw each itr

trap "echo 'I am invincible!!!'" SIGTERM
while true; do
      echo "To infinity and beyond"
      sleep 2
done
