#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file.

while IFS=: read -r username password uid gid user_info homedir shell; do
  echo "The user $username is part of the $gid gang,"\
  "lives in $homedir and rides $shell."\
  "User ID's place is protected by the passcode $password,"\
  "more info about the user here: $user_info"
done < /etc/passwd
