#!/usr/bin/env bash
# Bash script that displays "Best School" 10 times using a while loop.
#   for the 9th iteration, displays "Best School" and then "Hi" on a new line

count=1

while [ $count -le 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Best School"
    echo "Hi"
  fi
    echo "Best School"
    (( count++ ))
done
