#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 in addition to:
#   "bad luck from China" for the 4th iteration
#   "bad luck from Japan" for the 9th iteration
#   "bad luck from Italy" for the 17th loop iteration

count=0

while [ $count -lt 20 ]
do
  case $((count++)) in
    3) echo "4 bad luck from China" ;;
    8) echo "9 bad luck from Japan" ;;
    16) echo "17 bad luck from Italy" ;;
  esac
  echo "$count"
  ((count++))
done
