#!/usr/bin/env bash
# Script that displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hour=0

while [ $hour -lt 13 ]
do
    minute=1
    while [ $minute -lt 60 ]
    do
        echo "$hour:$minute"
        (( minute++ ))
    done
    (( hour++ ))
done
