#!/usr/bin/env bash
# Script that displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash.

list=$(ls)
for i in $list;
do
  if [[ "$i" != .* ]]
  then
    echo "$(echo "$i" | cut -d '-' -f 2-)"
  fi
done
